# Generated by Django 5.0 on 2023-12-23 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
