# Generated by Django 5.0 on 2023-12-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0004_posts_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Post Pic"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="profile picture"
            ),
        ),
    ]
